version: "3.9"

services:

  user_db:
    container_name: "user_db"
    image: "postgres"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_PASSWORD=root
    volumes:
      - user_db-data:/var/lib/postgresql/data

volumes:
  user_db-data:
    driver: local
