spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/user_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
    hikari:
      auto-commit: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
  sql:
    init:
      mode: always
      platform: postgres




springdoc:
  packagesToScan: com.giveandtake.userService

giveandtake:
  app:
    jwtSecret: ${JWT_SECRET:secretKey}
    jwtExpirationMs: ${JWT_EXPIRE_MS:3600000}
    adminEmail: ${ADMIN_EMAIL:admin@gmail.com}
    adminPassword: ${ADMIN_PASSWORD:admin}
